# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Tools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Tools

 
  pod 'YTKNetwork', '~> 3.0.4'

  pod 'Masonry', '~> 1.1.0'
  pod 'RealReachability', '~> 1.3.0'
    
  pod 'SDWebImage', '~> 5.8.4'
  pod 'SDWebImageWebPCoder', '~> 0.6.1'
  
  pod 'JXCategoryView', '~> 1.5.7'
  pod 'JXPagingView/Pager', '~> 2.0.13'
  pod 'MJRefresh', '~> 3.1.15.7'
  pod 'SVGAPlayer', '~> 2.5.4'
  
  pod 'YTKKeyValueStore', '~> 0.1.2'
#  pod 'SJVideoPlayer', '~> 3.2.6'
  
  pod 'FDFullscreenPopGesture', '~> 1.1'
  pod 'IQKeyboardManager','~> 6.5.6'
  
  pod 'FMDB', '~> 2.7.5'
  pod 'YYImage', '~> 1.0.4'
  pod 'YYModel', '~> 1.0.4'
  pod 'YYCategories', '~> 1.0.4'
  
  
  pod 'MJExtension', '~> 3.2.2'
#  pod 'MBProgressHUD'//已经手动集成
  pod 'SVProgressHUD', '~> 2.2.5'

  
#  pod 'JQFMDB'
  
  #腾讯超级播放器
#  pod 'SuperPlayer', '~> 3.2.7'
  
  pod 'BlocksKit', '~> 2.2.5'

  pod 'FLEX', '~> 3.1.2', :configurations => ['Debug']

  
end
